// app/privacy/page.tsx
import React from "react";

export const metadata = {
  title: "Privacy Policy – Fizzpoint",
  description: "Privacy Policy for Fizzpoint by Gnbeverages LLC",
};

export default function Page() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-[#0b1220] via-[#0d1a40] to-[#1443FF] text-white">
      <div className="mx-auto max-w-4xl px-6 py-16 md:px-10 space-y-8">
        {/* Header */}
        <header>
          <div className="mb-4 h-1 w-20 rounded-full bg-[#1443FF]" />
          <h1 className="text-3xl font-bold md:text-4xl">
            Privacy Policy for Fizzpoint
          </h1>
          <p className="mt-2 text-sm text-white/80">
            Last updated: August 31, 2025
          </p>
        </header>

        {/* Body */}
        <section className="rounded-xl bg-white/5 p-6 shadow-lg space-y-4">
          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the Privacy Policy
            Generator.
          </p>
        </section>

        <section className="rounded-xl bg-white/5 p-6 shadow-lg space-y-4">
          <h2 className="text-xl font-semibold">
            Interpretation and Definitions
          </h2>
          <h3 className="text-lg font-semibold">Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 className="text-lg font-semibold">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Account means a unique account created for You to access our
              Service or parts of our Service.
            </li>
            <li>
              Affiliate means an entity that controls, is controlled by or is
              under common control with a party, where "control" means ownership
              of 50% or more of the shares, equity interest or other securities
              entitled to vote for election of directors or other managing
              authority.
            </li>
            <li>
              Application refers to Fizzpoint, the software program provided by
              the Company.
            </li>
            <li>Company refers to Gnbeverages LLC, Ulaanbaatar.</li>
            <li>Country refers to: Mongolia</li>
            <li>
              Device means any device that can access the Service such as a
              computer, a cellphone or a digital tablet.
            </li>
            <li>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </li>
            <li>Service refers to the Application.</li>
            <li>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third-party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </li>
            <li>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              You means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </li>
          </ul>
        </section>

        {/* === Collecting and Using Data === */}
        <section className="rounded-xl bg-white/5 p-6 shadow-lg space-y-4">
          <h2 className="text-xl font-semibold">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="text-lg font-semibold">Types of Data Collected</h3>
          <h4 className="text-base font-semibold">Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-base font-semibold">Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>
        </section>

        {/* === Information Collected while Using App === */}
        <section className="rounded-xl bg-white/5 p-6 shadow-lg space-y-4">
          <h3 className="text-lg font-semibold">
            Information Collected while Using the Application
          </h3>
          <p>
            While using Our Application, in order to provide features of Our
            Application, We may collect, with Your prior permission:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Pictures and other information from your Device's camera and photo
              library
            </li>
          </ul>
          <p>
            We use this information to provide features of Our Service, to
            improve and customize Our Service. The information may be uploaded
            to the Company's servers and/or a Service Provider's server or it
            may be simply stored on Your device.
          </p>
          <p>
            You can enable or disable access to this information at any time,
            through Your Device settings.
          </p>
        </section>

        {/* === Use of Personal Data, Retention, Transfer, Disclosure, etc. === */}
        {/* Таны өгсөн үлдсэн бүх текстүүдийг яг ижил байдлаар section болгон оруулна. */}

        <section className="rounded-xl bg-white/5 p-6 shadow-lg space-y-4">
          <h2 className="text-xl font-semibold">Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, You can contact
            us:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              By visiting this page on our website:{" "}
              <a
                href="https://fizzpoint/privacy"
                className="underline decoration-[#1443FF] underline-offset-4 hover:decoration-white"
              >
                munkh-erdene@gnbeverages.mn
              </a>
            </li>
          </ul>
          <p className="text-xs text-white/60">
            Generated using TermsFeed Privacy Policy Generator
          </p>
        </section>
      </div>
    </main>
  );
}
